//PART PROPERTIES
Property Name(txt);
Property Sequence(txt);
Property Left_Overhang(txt);
Property Right_Overhang(txt);
Property Type(txt);
Property Resistance(txt);
Property Level(txt);

//PART TYPES
Part reporter(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part terminator_r(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part promoter(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part gene(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part terminator(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part invertase_site(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part invertase_site_r(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part promoter_r(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part reporter_r(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part RBS(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
//Part type(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part gene_r(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);

//PARTS
terminator_r J61048_rev(.Name("J61048_rev"), .Sequence("tttcttttgggtatagcgtcgtggacagtcattcatctttctgcccctccaaaagcaaaaacccgccgaagcgggtttttacgtaaatcaggtgaaactgaccgataagccgg"), .Left_Overhang(""), .Right_Overhang(""), .Type("terminator_r"), .Resistance(""), .Level(""));
gene_r araC_rev(.Name("araC_rev"), .Sequence("ttatgacaacttgacggctacatcattcactttttcttcacaaccggcacggaactcgctcgggctggccccggtgcattttttaaatacccgcgagaaatagagttgatcgtcaaaaccaacattgcgaccgacggtggcgataggcatccgggtggtgctcaaaagcagcttcgcctggctgatacgttggtcctcgcgccagcttaagacgctaatccctaactgctggcggaaaagatgtgacagacgcgacggcgacaagcaaacatgctgtgcgacgctggcgatatcaaaattgctgtctgccaggtgatcgctgatgtactgacaagcctcgcgtacccgattatccatcggtggatggagcgactcgttaatcgcttccatgcgccgcagtaacaattgctcaagcagatttatcgccagcagctccgaatagcgcccttccccttgcccggcgttaatgatttgcccaaacaggtcgctgaaatgcggctggtgcgcttcatccgggcgaaagaaccccgtattggcaaatattgacggccagttaagccattcatgccagtaggcgcgcggacgaaagtaaacccactggtgataccattcgcgagcctccggatgacgaccgtagtgatgaatctctcctggcgggaacagcaaaatatcacccggtcggcaaacaaattctcgtccctgatttttcaccaccccctgaccgcgaatggtgagattgagaatataacctttcattcccagcggtcggtcgataaaaaaatcgagataaccgttggcctcaatcggcgttaaacccgccaccagatgggcattaaacgagtatcccggcagcaggggatcattttgcgcttcagccat"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene_r"), .Resistance(""), .Level(""));
invertase_site attB_Bxb1(.Name("attB_Bxb1"), .Sequence("TCGGCCGGCTTGTCGACGACGGCGGTCTCCGTCGTCAGGATCATCCGGGC"), .Left_Overhang(""), .Right_Overhang(""), .Type("invertase_site"), .Resistance(""), .Level(""));
promoter pBAD(.Name("pBAD"), .Sequence("acattgattatttgcacggcgtcacactttgctatgccatagcatttttatccataagattagcggatcctacctgacgctttttatcgcaactctctactgtttctccatacccgtttttttgggctagc"), .Left_Overhang(""), .Right_Overhang(""), .Type("promoter"), .Resistance(""), .Level(""));
gene RESET_Integrase(.Name("RESET_Integrase"), .Sequence("GTGAGAGCCCTGGTAGTCATCCGCCTGTCCCGCGTCACCGATGCTACGACTTCACCGGAGCGTCAGCTGGAGTCTTGCCAGCAGCTCTGCGCCCAGCGCGGCTGGGACGTCGTCGGGGTAGCGGAGGATCTGGACGTCTCCGGGGCGGTCGATCCGTTCGACCGGAAGCGCAGACCGAACCTGGCCCGGTGGCTAGCGTTCGAGGAGCAACCGTTTGACGTGATCGTGGCGTACCGGGTAGATCGGTTGACCCGATCGATCCGGCATCTTCAGCAGCTGGTCCACTGGGCCGAGGACCACAAGAAGCTGGTCGTCTCCGCGACCGAAGCGCACTTCGATACGACGACGCCGTTTGCGGCGGTCGTCATCGCGCTTATGGGAACGGTGGCGCAGATGGAATTAGAAGCGATCAAAGAGCGGAACCGTTCGGCTGCGCATTTCAATATCCGCGCCGGGAAATACCGAGGATCCCTGCCGCCGTGGGGATACCTGCCTACGCGCGTGGACGGGGAGTGGCGGCTGGTGCCGGACCCTGTGCAGCGAGAGCGCATCCTCGAGGTGTATCACCGCGTCGTCGACAACCACGAGCCGCTGCATCTGGTGGCCCACGACCTGAACCGGCGTGGTGTCCTGTCGCCGAAGGACTACTTCGCGCAGCTGCAAGGCCGCGAGCCGCAGGGCCGGGAGTGGTCGGCTACCGCGCTGAAGCGATCGATGATCTCCGAGGCGATGCTCGGGTACGCGACTCTGAACGGTAAGACCGTCCGAGACGACGACGGAGCCCCGCTGGTGCGGGCTGAGCCGATCCTGACCCGTGAGCAGCTGGAGGCGCTGCGCGCCGAGCTCGTGAAGACCTCCCGGGCGAAGCCCGCGGTGTCTACCCCGTCGCTGCTGCTGCGGGTGTTGTTCTGCGCGGTGTGCGGGGAGCCCGCGTACAAGTTCGCCGGGGGAGGACGTAAGCACCCGCGCTACCGCTGCCGCTCGATGGGGTTCCCGAAGCACTGCGGGAACGGCACGGTGGCGATGGCCGAGTGGGACGCGTTCTGCGAGGAGCAGGTACTGGATCTGCTCGGGGACGCGGAGCGTCTGGAGAAAGTCTGGGTAGCGGGCTCGGACTCCGCGGTCGAACTCGCGGAGGTGAACGCGGAGCTGGTGGACCTGACGTCGCTGATCGGCTCCCCGGCCTACCGGGCGGGCTCTCCGCAGCGAGAAGCACTGGATGCCCGTATTGCGGCGCTGGCCGCGCGGCAAGAGGAGCTGGAGGGCCTGGAGGCTCGCCCGTCTGGCTGGGAGTGGCGCGAGACCGGGCAGCGGTTCGGGGACTGGTGGCGGGAGCAGGACACCGCGGCAAAGAACACCTGGCTTCGGTCGATGAACGTTCGGCTGACGTTCGACGTCCGCGGCGGGCTGACTCGCACGATCGACTTCGGGGATCTTCAGGAGTACGAGCAGCATCTCAGGCTCGGCAGCGTGGTCGAACGGCTACACACCGGGATGTCGACCGGCGCAGCAAACGACGAAAACTACGCTGCTCGTCATTAATAA"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene"), .Resistance(""), .Level(""));
terminator J61048(.Name("J61048"), .Sequence("ccggcttatcggtcagtttcacctgatttacgtaaaaacccgcttcggcgggtttttgcttttggaggggcagaaagatgaatgactgtccacgacgctatacccaaaagaaa"), .Left_Overhang(""), .Right_Overhang(""), .Type("terminator"), .Resistance(""), .Level(""));
reporter_r mKate2_rev(.Name("mKate2_rev"), .Sequence("ttatcaacgatgtcctaatttcgacggaaggtcacaataacgggctacggctacttcatgttgttcaacgtaggtttctttatcagcttctttaatacgttctaagcgacgatcaacatagtatactccaggcattttaaggtttttagcgggttttttggaacgataggttgttttcaggttgcagattaaatgaccgcctccaactaatttcagtgccatgtctgcgcgtccttctaagccaccgtccgcaggatataaggtttctgttgatgcttcccaaccaagagtttttttttgcattacgggtccgttactcgggaaatttacgccacggattttaacattgtaaatcagacagccatcttgtaaactcgtatcttgagttgctgtaagtacaccgccatcttcataagttgttacacgttcccaggtaaagccttcaggaaaggactgtttaaaaaagtcaggaatgccttgggtgtgattgataaaagttttagacccgtacataaagctcgttgcgagaatgtcaaacgcaaagggcaggggtccaccttcaactgctttgatgcgcattgtttgtgtgccttcatatggtttaccttcaccttcggatgtgcatttgaaatgatgattgttgacagtaccttccatatataatttcatgtgcatattttctttaattaattctga"), .Left_Overhang(""), .Right_Overhang(""), .Type("reporter_r"), .Resistance(""), .Level(""));
promoter_r J23119_rev(.Name("J23119_rev"), .Sequence("cgatcgtaatatggatcctgactcgatcgacagtt"), .Left_Overhang(""), .Right_Overhang(""), .Type("promoter_r"), .Resistance(""), .Level(""));
invertase_site_r attR_Bxb1_rev(.Name("attR_Bxb1_rev"), .Sequence("GCCCGGATGATCCTGACGACGGAGACCGCGGTGGTTGACCAGACAAACCACGA"), .Left_Overhang(""), .Right_Overhang(""), .Type("invertase_site_r"), .Resistance(""), .Level(""));
terminator B0014(.Name("B0014"), .Sequence("tcacactggctcaccttcgggtgggcctttctgcgtttatatactagagagagaatataaaaagccagattattaatccggcttttttattattt"), .Left_Overhang(""), .Right_Overhang(""), .Type("terminator"), .Resistance(""), .Level(""));
reporter Superfolder_gfp(.Name("Superfolder_gfp"), .Sequence("atgcgtaaaggcgaagagctgttcactggtgtcgtccctattctggtggaactggatggtgatgtcaacggtcataagttttccgtgcgtggcgagggtgaaggtgacgcaactaatggtaaactgacgctgaagttcatctgtactactggtaaactgccggtaccttggccgactctggtaacgacgctgacttatggtgttcagtgctttgctcgttatccggaccatatgaagcagcatgacttcttcaagtccgccatgccggaaggctatgtgcaggaacgcacgatttcctttaaggatgacggcacgtacaaaacgcgtgcggaagtgaaatttgaaggcgataccctggtaaaccgcattgagctgaaaggcattgactttaaagaagacggcaatatcctgggccataagctggaatacaattttaacagccacaatgtttacatcaccgccgataaacaaaaaaatggcattaaagcgaattttaaaattcgccacaacgtggaggatggcagcgtgcagctggctgatcactaccagcaaaacactccaatcggtgatggtcctgttctgctgccagacaatcactatctgagcacgcaaagcgttctgtctaaagatccgaacgagaaacgcgatcatatggttctgctggagttcgtaaccgcagcgggcatcacgcatggtatggatgaactgtacaaatgatga"), .Left_Overhang(""), .Right_Overhang(""), .Type("reporter"), .Resistance(""), .Level(""));
RBS 6N_RBS(.Name("6N_RBS"), .Sequence("GCGGCTTTCACACTTGGGGGCTAGC"), .Left_Overhang(""), .Right_Overhang(""), .Type("RBS"), .Resistance(""), .Level(""));
RBS B0031(.Name("B0031"), .Sequence("tcacacaggaaacc"), .Left_Overhang(""), .Right_Overhang(""), .Type("RBS"), .Resistance(""), .Level(""));
promoter J23119(.Name("J23119"), .Sequence("ttgacagctagctcagtcctaggtataatgctagc"), .Left_Overhang(""), .Right_Overhang(""), .Type("promoter"), .Resistance(""), .Level(""));
//type Name(.Name("Name"), .Sequence("Sequence"), .Left_Overhang("Left_Overhang"), .Right_Overhang("Right_Overhang"), .Type("type"), .Resistance(""), .Level(""));
gene Bxb1_Integrase(.Name("Bxb1_Integrase"), .Sequence("atggccggcagagccctggtagtcatccgcctgtcccgcgtcaccgatgctacgacttcaccggagcgtcagctggagtcttgccagcagctctgcgcccagcgcggctgggacgtcgtcggggtagcggaggatctggacgtctccggggcggtcgatccgttcgaccggaagcgcagaccgaacctggcccggtggctagcgttcgaggagcaaccgtttgacgtgatcgtggcgtaccgggtagatcggttgacccgatcgatccggcatcttcagcagctggtccactgggccgaggaccacaagaagctggtcgtctccgcgaccgaagcgcacttcgatacgacgacgccgtttgcggcggtcgtcatcgcgcttatgggaacggtggcgcagatggaattagaagcgatcaaagagcggaaccgttcggctgcgcatttcaatatccgcgccgggaaataccgaggatccctgccgccgtggggatacctgcctacgcgcgtggacggggagtggcggctggtgccggaccctgtgcagcgagagcgcatcctcgaggtgtatcaccgcgtcgtcgacaaccacgagccgctgcatctggtggcccacgacctgaaccggcgtggtgtcctgtcgccgaaggactacttcgcgcagctgcaaggccgcgagccgcagggccgggagtggtcggctaccgcgctgaagcgatcgatgatctccgaggcgatgctcgggtacgcgactctgaacggtaagaccgtccgagacgacgacggagccccgctggtgcgggctgagccgatcctgacccgtgagcagctggaggcgctgcgcgccgagctcgtgaagacctcccgggcgaagcccgcggtgtctaccccgtcgctgctgctgcgggtgttgttctgcgcggtgtgcggggagcccgcgtacaagttcgccgggggaggacgtaagcacccgcgctaccgctgccgctcgatggggttcccgaagcactgcgggaacggcacggtggcgatggccgagtgggacgcgttctgcgaggagcaggtactggatctgctcggggacgcggagcgtctggagaaagtctgggtagcgggctcggactccgcggtcgaactcgcggaggtgaacgcggagctggtggacctgacgtcgctgatcggctccccggcctaccgggcgggctctccgcagcgagaagcactggatgcccgtattgcggcgctggccgcgcggcaagaggagctggagggcctggaggctcgcccgtctggctgggagtggcgcgagaccgggcagcggttcggggactggtggcgggagcaggacaccgcggcaaagaacacctggcttcggtcgatgaacgttcggctgacgttcgacgtccgcggcgggctgactcgcacgatcgacttcggggatcttcaggagtacgagcagcatctcaggctcggcagcgtggtcgaacggctacacaccgggatgtcgaccggttaa"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene"), .Resistance(""), .Level(""));
gene Bxb1_Excisionase(.Name("Bxb1_Excisionase"), .Sequence("atgactcagcgtatcgtctttctacccgatactcagttgcctttcgaggcgcgcaaagagatgcaagcggtcatccgcttcatcggggatgtccagccgtacggcgtggtacatatcggtgacgtcctagacctgccgcagccctcgcgctggaaccggggaaccaagggcgagttcgagggctcggtgtaccgcgacgcggactacgccaagaagaacctgatggagccgctgcgcaaggtctacgacggctggatcgggatgcacgagggcaaccacgatctgcgagcccgcgagtacctggccaagaacgcaccggccctggagggtacgcacgctttcgacatcgacgtgctgctcgacttcgacgggttcggtgtggagctgctgcctgacttctacgacatcgctccgggctggatctccactcacgggcacatgggcaagatgacgctatcccagatcgccggatcgacagcgctcaacggtgccaagaagttcggcaagtccgtggtctgcggccacacgcaccggcaggctgtcgtctcgcactcgttcgggtacggcggctcggtgcgcaagaccgtcaccggcatggaagtcgggcacctgatggacatgaagaaggccaactatctaaagggcggagccgggaactggcagatgggcttcgggatgctcacggtcgacggcaagcatgtcaaggctgagatcgtcccgatcctgggaggcaagttcaccgttgacggccaggtctgggaagtctag"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene"), .Resistance(""), .Level(""));
gene SET_Integrase(.Name("SET_Integrase"), .Sequence("GTGAGAGCCCTGGTAGTCATCCGCCTGTCCCGCGTCACCGATGCTACGACTTCACCGGAGCGTCAGCTGGAGTCTTGCCAGCAGCTCTGCGCCCAGCGCGGCTGGGACGTCGTCGGGGTAGCGGAGGATCTGGACGTCTCCGGGGCGGTCGATCCGTTCGACCGGAAGCGCAGACCGAACCTGGCCCGGTGGCTAGCGTTCGAGGAGCAACCGTTTGACGTGATCGTGGCGTACCGGGTAGATCGGTTGACCCGATCGATCCGGCATCTTCAGCAGCTGGTCCACTGGGCCGAGGACCACAAGAAGCTGGTCGTCTCCGCGACCGAAGCGCACTTCGATACGACGACGCCGTTTGCGGCGGTCGTCATCGCGCTTATGGGAACGGTGGCGCAGATGGAATTAGAAGCGATCAAAGAGCGGAACCGTTCGGCTGCGCATTTCAATATCCGCGCCGGGAAATACCGAGGATCCCTGCCGCCGTGGGGATACCTGCCTACGCGCGTGGACGGGGAGTGGCGGCTGGTGCCGGACCCTGTGCAGCGAGAGCGCATCCTCGAGGTGTATCACCGCGTCGTCGACAACCACGAGCCGCTGCATCTGGTGGCCCACGACCTGAACCGGCGTGGTGTCCTGTCGCCGAAGGACTACTTCGCGCAGCTGCAAGGCCGCGAGCCGCAGGGCCGGGAGTGGTCGGCTACCGCGCTGAAGCGATCGATGATCTCCGAGGCGATGCTCGGGTACGCGACTCTGAACGGTAAGACCGTCCGAGACGACGACGGAGCCCCGCTGGTGCGGGCTGAGCCGATCCTGACCCGTGAGCAGCTGGAGGCGCTGCGCGCCGAGCTCGTGAAGACCTCCCGGGCGAAGCCCGCGGTGTCTACCCCGTCGCTGCTGCTGCGGGTGTTGTTCTGCGCGGTGTGCGGGGAGCCCGCGTACAAGTTCGCCGGGGGAGGACGTAAGCACCCGCGCTACCGCTGCCGCTCGATGGGGTTCCCGAAGCACTGCGGGAACGGCACGGTGGCGATGGCCGAGTGGGACGCGTTCTGCGAGGAGCAGGTACTGGATCTGCTCGGGGACGCGGAGCGTCTGGAGAAAGTCTGGGTAGCGGGCTCGGACTCCGCGGTCGAACTCGCGGAGGTGAACGCGGAGCTGGTGGACCTGACGTCGCTGATCGGCTCCCCGGCCTACCGGGCGGGCTCTCCGCAGCGAGAAGCACTGGATGCCCGTATTGCGGCGCTGGCCGCGCGGCAAGAGGAGCTGGAGGGCCTGGAGGCTCGCCCGTCTGGCTGGGAGTGGCGCGAGACCGGGCAGCGGTTCGGGGACTGGTGGCGGGAGCAGGACACCGCGGCAAAGAACACCTGGCTTCGGTCGATGAACGTTCGGCTGACGTTCGACGTCCGCGGCGGGCTGACTCGCACGATCGACTTCGGGGATCTTCAGGAGTACGAGCAGCATCTCAGGCTCGGCAGCGTGGTCGAACGGCTACACACCGGGATGTCGtaa"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene"), .Resistance(""), .Level(""));
invertase_site_r attP_Bxb1_rev(.Name("attP_Bxb1_rev"), .Sequence("GGGTTTGTACCGTACACCACTGAGACCGCGGTGGTTGACCAGACAAACCACGA"), .Left_Overhang(""), .Right_Overhang(""), .Type("invertase_site_r"), .Resistance(""), .Level(""));
RBS RBS_50000(.Name("RBS_50000"), .Sequence("ACCTTAACAAACTACGGAGGTCAAC"), .Left_Overhang(""), .Right_Overhang(""), .Type("RBS"), .Resistance(""), .Level(""));
invertase_site attL_Bxb1(.Name("attL_Bxb1"), .Sequence("TCGGCCGGCTTGTCGACGACGGCGGTCTCAGTGGTGTACGGTACAAACCC"), .Left_Overhang(""), .Right_Overhang(""), .Type("invertase_site"), .Resistance(""), .Level(""));
promoter pTet(.Name("pTet"), .Sequence("tccctatcagtgatagagattgacatccctatcagtgatagagatactgagcac"), .Left_Overhang(""), .Right_Overhang(""), .Type("promoter"), .Resistance(""), .Level(""));
