//created on: May 11, 2014
package org.cidarlab.eugene.genomatica

//list any import classes here.
import org.cidarlab.eugene.dom.Part;
import org.cidarlab.eugene.dom.Device;
import java.lang.String;

//declare any global variables here

/*
 * device[0].sequence.size() + device[1].sequence.size() + device[2].sequence.size() <= maxlength
 * /\
 * device[3].sequence.size() + device[4].sequence.size() + device[5].sequence.size() <= maxlength
 */

rule "sequence length"
	dialect "java"
    when
    	$d : Device (
    		// device[0].sequence 
    		$component0 : components[0],
    		$component0[0] instanceof Part,
    		((Part)$component0[0]).propertyValues["sequence"] != null,
    		   
    		// device[1].sequence    		
    		$component1 : components[1],
    		$component1[0] instanceof Part,
    		((Part)$component1[0]).propertyValues["sequence"] != null,
    		
    		// device[2].sequence    		
    		$component2 : components[2],
    		$component2[0] instanceof Part,
    		((Part)$component2[0]).propertyValues["sequence"] != null,

			// device[0].sequence.length + device[1].sequence.length + device[2].sequence.length <= 3
    		((Part)$component0[0]).propertyValues["sequence"].txt.length() + 
    		((Part)$component1[0]).propertyValues["sequence"].txt.length() + 
    		((Part)$component2[0]).propertyValues["sequence"].txt.length() <= 3,


			// AND (/\)

    		// device[3].sequence 
    		$component3 : components[3], 
    		$component3[0] instanceof Part,
    		((Part)$component3[0]).propertyValues["sequence"] != null,
    		    		
    		// device[4].sequence 
    		$component4 : components[4], 
    		$component4[0] instanceof Part,
    		((Part)$component4[0]).propertyValues["sequence"] != null,
    		
    		// device[5].sequence 
    		$component5 : components[5], 
    		$component5[0] instanceof Part,
    		((Part)$component5[0]).propertyValues["sequence"] != null,

			// device[3].sequence.length + device[4].sequence.length + device[5].sequence.length <= 3
    		((Part)$component3[0]).propertyValues["sequence"].txt.length() + 
    		((Part)$component4[0]).propertyValues["sequence"].txt.length() + 
    		((Part)$component5[0]).propertyValues["sequence"].txt.length() <= 3
   		)
    then
		System.out.println($d);
end
