package org.cidarlab.sparrow.rule;

/**
 * A SparrowQuery queries the WM for facts. 
 * It's a composition of Eugene Expression rules,
 * e.g. Promoter.Strength > 5 /\ Promoter.RepressedBy == "TetR"
 *  
 * Compared to a SparrowRule, a SparrowQuery does NOT have a RHS (i.e. conclusion/action).
 * 
 * @author Ernst Oberortner
 *
 */
public class SparrowQuery {

	private String name;
	
	/*
	 * the rule is generated by the Eugene2Sparrow compiler
	 */
	private String query;
	
	public SparrowQuery(String name, String query) {
		this.name = name;
		this.query = query;
	}

	public String getName() {
		return this.name;
	}
	
	public String getQuery() {
		return this.query;
	}
	
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(this.getName()).append(" #= ").append(this.getQuery());		
		return sb.toString();
	}
}
