//PART PROPERTIES
Property Name(txt);
Property Sequence(txt);
Property Left_Overhang(txt);
Property Right_Overhang(txt);
Property Type(txt);
Property Resistance(txt);
Property Level(txt);

//PART TYPES
Part reporter(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part promoter(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part gene(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
Part terminator(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
PartType RBS(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);

/*
 * Q: do we need this?
 * Part type(Name, Sequence, Left_Overhang, Right_Overhang, Type, Resistance, Level);
 * type Name(.Name("Name"), .Sequence("Sequence"), .Left_Overhang("Left_Overhang"), .Right_Overhang("Right_Overhang"), .Type("type"), .Resistance(""), .Level(""));
  */
 
//PARTS
promoter pBAD(.Name("pBAD"), .Sequence("agaaaccaattgtccatattgcatcagacattgccgtcactgcgtcttttactggctcttctcgctaaccaaaccggtaaccccgcttattaaaagcattctgtaacaaagcgggaccaaagccatgacaaaaacgcgtaacaaaagtgtctataatcacggcagaaaagtccacattgattatttgcacggcgtcacactttgctatgccatagcatttttatccataagattagcggatcctacctg"), .Left_Overhang(""), .Right_Overhang(""), .Type("promoter"), .Resistance(""), .Level(""));
promoter pRhl(.Name("pRhl"), .Sequence("tcctgtgaaatctggcagttaccgttagctttcgaattggctaaaaagtgttc"), .Left_Overhang(""), .Right_Overhang(""), .Type("promoter"), .Resistance(""), .Level(""));
promoter pTet2(.Name("pTet2"), .Sequence("tccctatcagtgatagagattgacatccctatcagtgatagatataatgagcac"), .Left_Overhang(""), .Right_Overhang(""), .Type("promoter"), .Resistance(""), .Level(""));
promoter pLas(.Name("pLas"), .Sequence("tttcttcgagcctagcaagggtccgggttcaccgaaatctatctcatttgctagttataaaattatga"), .Left_Overhang(""), .Right_Overhang(""), .Type("promoter"), .Resistance(""), .Level(""));
promoter pcI(.Name("pcI"), .Sequence("taacaccgtgcgtgttgactattttacctctggcggtgataatggttgc"), .Left_Overhang(""), .Right_Overhang(""), .Type("promoter"), .Resistance(""), .Level(""));
promoter J23117(.Name("J23117"), .Sequence("ttgacagctagctcagtcctagggattgtgctagc"), .Left_Overhang(""), .Right_Overhang(""), .Type("promoter"), .Resistance(""), .Level(""));

gene lasR(.Name("lasR"), .Sequence("atggccttggttgacggttttcttgagctggaacgctcaagtggaaaattggagtggagcgccatcctccagaagatggcgagcgaccttggattctcgaagatcctgttcggcctgttgcctaaggacagccaggactacgagaacgccttcatcgtcggcaactacccggccgcctggcgcgagcattacgaccgggctggctacgcgcgggtcgacccgacggtcagtcactgtacccagagcgtactgccgattttctgggaaccgtccatctaccagacgcgaaagcagcacgagttcttcgaggaagcctcggccgccggcctggtgtatgggctgaccatgccgctgcatggtgctcgcggcgaactcggcgcgctgagcctcagcgtggaagcggaaaaccgggccgaggccaaccgtttcatagagtcggtcctgccgaccctgtggatgctcaaggactacgcactgcaaagcggtgccggactggccttcgaacatccggtcagcaaaccggtggttctgaccagccgggagaaggaagtgttgcagtggtgcgccatcggcaagaccagttgggagatatcggttatccgaacatccggtcagcaaaccggtggttctgaccagccgggagaaggaagtgttgcagtggtgcgccatcggcaagaccagttgggagatatcggttatccgaacatccggtcagcaaaccggtggttctgaccagccgggagaaggaagtgttgcagtggtgcgccatcggcaagaccagttgggagatatcggttatctgcaactgctcggaagccaatgtgaacttccatatgggaaatattcggcggaagttcggtgtgacctcccgccgcgtagcggccattatggccgttaatttgggtcttattactctc"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene"), .Resistance(""), .Level(""));
gene araC(.Name("araC"), .Sequence("atggctgaagcgcaaaatgatcccctgctgccgggatactcgtttaatgcccatctggtggcgggtttaacgccgattgaggccaacggttatctcgatttttttatcgaccgaccgctgggaatgaaaggttatattctcaatctcaccattcgcggtcagggggtggtgaaaaatcagggacgagaatttgtttgccgaccgggtgatattttgctgttcccgccaggagagattcatcactacggtcgtcatccggaggctcgcgaatggtatcaccagtgggtttactttcgtccgcgcgcctactggcatgaatggcttaactggccgtcaatatttgccaatacggggttctttcgcccggatgaagcgcaccagccgcatttcagcgacctgtttgggcaaatcattaacgccgggcaaggggaagggcgctattcggagctgctggcgataaatctgcttgagcaattgttactgcggcgcatggaagcgattaacgagtcgctccatccaccgatggataatcgggtacgcgaggcttgtcagtacatcagcgatcacctggcagacagcaattttgatatcgccagcgtcgcacagcatgtttgcttgtcgccgtcgcgtctgtcacatcttttccgccagcagttagggattagcgtcttaagctggcgcgaggaccaacgtatcagccaggcgaagctgcttttgagcaccacccggatgcctatcgccaccgtcggtcgcaatgttggttttgacgatcaactctatttctcgcgggtatttaaaaaatgcaccggggccagcccgagcgagttccgtgccggttgtgaagaaaaagtgaatgatgtagccgtcaagttgtcataa"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene"), .Resistance(""), .Level(""));
gene rhlR(.Name("rhlR"), .Sequence("atgaggaatgacggaggctttttgctgtggtgggacggtttgcgtagcgagatgcagccgatccacgacagccagggcgtgttcgccgtcctggaaaaggaagtgcggcgcctgggcttcgattactacgcctatggcgtgcgccacacgattcccttcacccggccgaagaccgaggtccatggcacctatcccaaggcctggctggagcgataccagatgcagaactacggggccgtggatccggcgatcctcaacggcctgcgctcctcggaaatggtggtctggagcgacagcctgttcgaccagagccggatgctctggaacgaggctcgcgattggggcctctgtgtcggcgcgaccttgccgatccgcgcgccgaacaatttgctcagcgtgctttccgtggcgcgcgaccagcagaacatctccagcttcgagcgcgaggaaatccgcctgcggctgcgttgcatgatcgagttgctgacccagaagctgaccgacctggagcatccgatgctgatgtccaacccggtctgcctgagccatcgcgaacgcgagatcctgcaatggaccgccgacggcaagagttccggggaaatcgccatcatcctgagcatctccgagagcacggtgaacttccaccacaagaacatccagaagaagttcgacgcgccgaacaagacgctggctgccgcctacgccgcggcgctgggtctcatc"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene"), .Resistance(""), .Level(""));
gene cI(.Name("cI"), .Sequence("atgagcacaaaaaagaaaccattaacacaagagcagcttgaggacgcacgtcgccttaaagcaatttatgaaaaaaagaaaaatgaacttggcttatcccaggaatctgtcgcagacaagatggggatggggcagtcaggcgttggtgctttatttaatggcatcaatgcattaaatgcttataacgccgcattgcttgcaaaaattctcaaagttagcgttgaagaatttagcccttcaatcgccagagaaatctacgagatgtatgaagcggttagtatgcagccgtcacttagaagtgagtatgagtaccctgttttttctcatgttcaggcagggatgttctcacctgagcttagaacctttaccaaaggtgatgcggagagatgggtaagcacaaccaaaaaagccagtgattctgcattctggcttgaggttgaaggtaattccatgaccgcaccaacaggctccaagccaagctttcctgacggaatgttaattctcgttgaccctgagcaggctgttgagccaggtgatttctgcatagccagacttgggggtgatgagtttaccttcaagaaactgatcagggatagcggtcaggtgtttttacaaccactaaacccacagtacccaatgatcccatgcaatgagagttgttccgttgtggggaaagttatcgctagtcagtggcctgaagagacgtttggcgctgcaaacgacgaaaactacgctttagtagcttaataa"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene"), .Resistance(""), .Level(""));
gene lasI(.Name("lasI"), .Sequence("atgatcgttcagatcggtcgtcgtgaagagttcgacaaaaaactgctgggtgaaatgcacaaactgcgtgctcaggttttcaaagaacgtaaaggttgggacgtttccgttatcgacgaaatggaaatcgacggttacgacgctctgtccccgtactacatgctgatccaggaagacaccccggaagctcaggttttcggttgctggcgtatcttcgacaccaccggtccgtacatgctgaaaaacaccttcccggaactgctgcacggtaaagaagctccgtgctccccgcacatctgggaactgtcccgtttcgctatcaactccggtcagaaaggttccctgggtttctccgactgcaccctggaagctatgcgtgctctggctcgttactccttgcagaacgacatccagaccctggttaccgttaccaccgttggtgttgaaaaaatgatgatccgtgctggtctggacgtttcccgtttcggtccgcacctgaaaatcggtatcgaacgtgctgttgctctgcgtatcgaactgaacgctaaaacccagatcgctctgtacggtggtgttctggttgaacagcgtctggctgtttcc"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene"), .Resistance(""), .Level(""));
gene tetR(.Name("tetR"), .Sequence("atgtccagattagataaaagtaaagtgattaacagcgcattagagctgcttaatgaggtcggaatcgaaggtttaacaacccgtaaactcgcccagaagctaggtgtagagcagcctacattgtattggcatgtaaaaaataagcgggctttgctcgacgccttagccattgagatgttagataggcaccatactcacttttgccctttagaaggggaaagctggcaagattttttacgtaataacgctaaaagttttagatgtgctttactaagtcatcgcgatggagcaaaagtacatttaggtacacggcctacagaaaaacagtatgaaactctcgaaaatcaattagcctttttatgccaacaaggtttttcactagagaatgcattatatgcactcagcgctgtggggcattttactttaggttgcgtattggaagatcaagagcatcaagtcgctaaagaagaaagggaaacacctactactgatagtatgccgccattattacgacaagctatcgaattatttgatcaccaaggtgcagagccagccttcttattcggccttgaattgatcatatgcggattagaaaaacaacttaaatgtgaaagtgggtcctaa"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene"), .Resistance(""), .Level(""));
gene rhlI(.Name("rhlI"), .Sequence("atgatcgaactgctgtccgaatccctggaaggtctgtccgctgctatgatcgctgaactgggtcgttaccgtcaccaggttttcatcgaaaaactgggttgggacgttgtttccacctcccgtgttcgtgaccaggagttcgaccagttcgaccacccgcagacccgttacatcgttgctatgtcccgtcagggtatctgcggttgcgctcgtctgctgccgaccaccgacgcttacctgctgaaagacgttttcgcttacctgtgctccgaaaccccgccgtccgacccgtccgtttgggaactgtcccgttacgctgcttccgctgctgacgacccgcagctggctatgaaaatcttctggtcctccctccagtgcgcttggtacctgggtgcttcctccgttgttgctgttaccaccaccgctatggaacgttacttcgttcgtaacggtgttatcctccagcgtctgggtccgccgcagaaagttaaaggtgaaaccctggttgctatctccttcccggcttaccaggaacgtggtctggaaatgctgctgcgttaccacccggaatggctccagggtgttccgctgtccatggctgtt"), .Left_Overhang(""), .Right_Overhang(""), .Type("gene"), .Resistance(""), .Level(""));

reporter eyfp(.Name("eyfp"), .Sequence("atggtgagcaagggcgaggagctgttcaccggggtggtgcccatcctggtcgagctggacggcgacgtaaacggccacaagttcagcgtgtccggcgagggcgagggcgatgccacctacggcaagctgaccctgaagttcatctgcaccaccggcaagctgcccgtgccctggcccaccctcgtgaccaccttcggctacggcctgcaatgcttcgcccgctaccccgaccacatgaagctgcacgacttcttcaagtccgccatgcccgaaggctacgtccaggagcgcaccatcttcttcaaggacgacggcaactacaagacccgcgccgaggtgaagttcgagggcgacaccctggtgaaccgcatcgagctgaagggcatcgacttcaaggaggacggcaacatcctggggcacaagctggagtacaactacaacagccacaacgtctatatcatggccgacaagcagaagaacggcatcaaggtgaacttcaagatccgccacaacatcgaggacggcagcgtgcagctcgccgaccactaccagcagaacacccccatcggcgacggccccgtgctgctgcccgacaaccactacctgagctaccagtccgccctgagcaaagaccccaacgagaagcgcgatcacatggtcctgctggagttcgtgaccgccgccgggatcactctcggcatggacgagctgtacaagtaataa"), .Left_Overhang(""), .Right_Overhang(""), .Type("reporter"), .Resistance(""), .Level(""));

terminator T1TE(.Name("T1TE"), .Sequence("ccaggcatcaaataaaacgaaaggctcagtcgaaagactgggcctttcgttttatctgttgtttgtcggtgaacgctctctactagagtcacactggctcaccttcgggtgggcctttctgcgttta"), .Left_Overhang(""), .Right_Overhang(""), .Type("terminator"), .Resistance(""), .Level(""));
